### ISSUE TITLE
dataset release time

### ISSUE THREAD

**Issue by chenriwei** [afad-dataset/afad-dataset.github.io#2]
Hi, when do you plan to  release the dateaset?

**Comment by basuam** [comment]
Hi, 

First of all, thank you for the contribution to the age estimation researchers. 
This new database for asian individuals with more than 160k is really useful, specially when working with Deep Learning.

It would be really nice of you if you could help us with the estimated time you are planning to release the dataset.

Thank you very much for your help.

**Comment by YIFanH** [comment]
Hi,thank for you research on face age estimation,when do you plan to share the dataset? 
best wishes for you !

**Comment by ghost** [comment]
Hi, I am interested in your research on face age estimation, when do you plan to release the AFAD dataset?

**Comment by qingmeizhujiu** [comment]
> Hi, when do you plan to release the dateaset?

do you get it?  If that， please copy to me.   @chen ri tian
