### ISSUE TITLE
How to download afad dataset?

### ISSUE THREAD

**Issue by zhangqianhui** [afad-dataset/afad-dataset.github.io#3]
thanks for your answer!

**Comment by kli-casia** [comment]
I have the same question.

**Comment by ysc703** [comment]
thanks for your answer ++

**Comment by exgile** [comment]
How to download afad dataset?

**Comment by seungchul0406** [comment]
How to download afad dataset?

**Comment by javierlaporta** [comment]
How to download afad dataset?

**Comment by hoangng1996** [comment]
How can I download the dataset? Thanks

**Comment by liyi0040** [comment]
Have the same problem.
Is there any way to get the dataset? 
Thx a lot for your help!

**Comment by anujrohilla** [comment]
I also have the same question?

**Comment by jdcla** [comment]
Is there a public link yet? Unable to find this.
