### ISSUE TITLE
can you help me to download the dataset?thank you!

### ISSUE THREAD

**Issue by zouying-sjtu** [afad-dataset/afad-dataset.github.io#8]
my email is 975104083@qq.com      you can contact with me with this email.

**Comment by HoiM** [comment]
This is weird. A never released 'public' dataset.

**Comment by John-niu-07** [comment]
https://github.com/afad-dataset/tarball
https://github.com/afad-dataset/tarball-lite

**Comment by zouying-sjtu** [comment]
thanks
